services:
  - type: web
    name: portfolio-api
    env: python
    pythonVersion: "3.11"
    plan: free

    buildCommand: pip install --upgrade pip && pip install --prefer-binary -r requirements.txt

    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
